version: "3.3"
services:
  smswithoutborders:
    image: "smswithoutborders"
    container_name: smswithoutborders
    build:
      context: .
    env_file:
      - .env
    network_mode: "host"
    ports:
      - "80:80"
